### ISSUE TITLE
Download JSON Schema button in pages doesn't work

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/models#90] opened 2019-09-20 20:24 UTC
The "Download JSON Schema" button in model pages doesn't work.

Example

https://models.accordproject.org/patents/patent.html

**Comment by jeromesimeon** [comment] 2019-11-11 19:31
This issue is a duplicate of #22 I'm closing it as such.

**Closed by jeromesimeon** 2019-11-11 19:31 UTC
Labels: Resolution: Duplicate 👯
